const light = {
    _default: '#000',
    comment: 'slategray',
    prolog: 'slategray',
    doctype: 'slategray',
    cdata: 'slategray',
    punctuation: '#999',
    namespace: {
        opacity: 0.7,
    },
    property: '#905',
    tag: '#905',
    boolean: '#905',
    number: '#905',
    constant: '#905',
    symbol: '#905',
    deleted: '#905',
    selector: '#690',
    'attr-name': '#690',
    string: '#690',
    char: '#690',
    builtin: '#690',
    inserted: '#690',
    operator: '#9a6e3a',
    entity: '#9a6e3a',
    url: '#9a6e3a',
    keyword: '#07a',
    'attr-value': '#07a',
    atrule: '#07a',
    function: '#DD4A68',
    'class-name': '#DD4A68',
    regex: '#e90',
    important: '#e90',
    variable: '#e90',
}

module.exports = light
